[[libsharp2]]
arch = "aarch64"
git-tree-sha1 = "58d3b8bd2451914fab2e78d555af894bb64a1b66"
os = "macos"

    [[libsharp2.download]]
    sha256 = "22d94c9a660c94a8393e42af1a83c987cf8c9a5b7c5b6a2454e9b8d4c86cf19d"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.2+0/libsharp2.v1.0.2.aarch64-apple-darwin.tar.gz"
[[libsharp2]]
arch = "aarch64"
git-tree-sha1 = "72f6eead7dc9cf8d68edb9c69c149fe9145e4e03"
libc = "glibc"
os = "linux"

    [[libsharp2.download]]
    sha256 = "ffd8d01f61c6f10ec9786ec198d6819e3b191909190664e3fab41cd6f491f646"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.2+0/libsharp2.v1.0.2.aarch64-linux-gnu.tar.gz"
[[libsharp2]]
arch = "aarch64"
git-tree-sha1 = "7bf3ce32e1f3c77e0505ce13006a9a6d1642922f"
libc = "musl"
os = "linux"

    [[libsharp2.download]]
    sha256 = "426b3a4e5463afdede284ada6e0d58798e6d49604f0cafcd88a976a692e8e7b4"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.2+0/libsharp2.v1.0.2.aarch64-linux-musl.tar.gz"
[[libsharp2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bdfeba4e77a67fb35d3a9696be8b3654eeacd28a"
libc = "glibc"
os = "linux"

    [[libsharp2.download]]
    sha256 = "4c60f657d8e9862deb70d472153b82963224f6c4325fdd1dae0bde56d1d11e4c"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.2+0/libsharp2.v1.0.2.armv6l-linux-gnueabihf.tar.gz"
[[libsharp2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b27fa212bc096fcfca960f945fe449330337ebe6"
libc = "musl"
os = "linux"

    [[libsharp2.download]]
    sha256 = "6ed99985006dd707e514e94d398ca40f3ff86222db6584213047ddb65dcda5aa"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.2+0/libsharp2.v1.0.2.armv6l-linux-musleabihf.tar.gz"
[[libsharp2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "33fefff5e8a3c96a5f4c296e315c78c29dfd7c88"
libc = "glibc"
os = "linux"

    [[libsharp2.download]]
    sha256 = "f8d40dd41e7b22d2866ac207a76c7619c23314fe45e14a17f6da1ce0f238cfd5"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.2+0/libsharp2.v1.0.2.armv7l-linux-gnueabihf.tar.gz"
[[libsharp2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "39db13a05e2c766d94e966c3a0ed0ddb5f4ec793"
libc = "musl"
os = "linux"

    [[libsharp2.download]]
    sha256 = "6dbb12bfd04598b5c6b2bf967eb3dbd3c91f1cb972c2b1546b8236f9ef990278"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.2+0/libsharp2.v1.0.2.armv7l-linux-musleabihf.tar.gz"
[[libsharp2]]
arch = "i686"
git-tree-sha1 = "3330f8f5f295d8662da6d797624095564ba77f9c"
libc = "glibc"
os = "linux"

    [[libsharp2.download]]
    sha256 = "3d1e4e5e97411349a534ae3401a79dcb369289b1b34f0de0c16dd9cb95d178f6"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.2+0/libsharp2.v1.0.2.i686-linux-gnu.tar.gz"
[[libsharp2]]
arch = "i686"
git-tree-sha1 = "cf12d5f27ffc3c189d2cf62851a71af683bcb06c"
libc = "musl"
os = "linux"

    [[libsharp2.download]]
    sha256 = "fcd9874d6996ad9129c4b18d079393efec5e88fccb530cd40c8a8fa64e2e1eee"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.2+0/libsharp2.v1.0.2.i686-linux-musl.tar.gz"
[[libsharp2]]
arch = "i686"
git-tree-sha1 = "6e5703153e531adbadca4cbfc98cae9728fdb232"
os = "windows"

    [[libsharp2.download]]
    sha256 = "686fdcfde0bc9863684e7f2f1fe20ce13e8143eada77b59cd5c054cbc15f390c"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.2+0/libsharp2.v1.0.2.i686-w64-mingw32.tar.gz"
[[libsharp2]]
arch = "powerpc64le"
git-tree-sha1 = "e2c70795df7cd2151956114978b8309012ee2029"
libc = "glibc"
os = "linux"

    [[libsharp2.download]]
    sha256 = "d2bb715e581de1218199e36820a3eb5cbc8c0f56429fd97f08f9c3200179939b"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.2+0/libsharp2.v1.0.2.powerpc64le-linux-gnu.tar.gz"
[[libsharp2]]
arch = "x86_64"
git-tree-sha1 = "6f1c8677c80e5e14bb2d6a844d5dfeb45f5eac95"
os = "macos"

    [[libsharp2.download]]
    sha256 = "b03bd15ae8c48d7e26a2e442e56cbe4e66565a4991d8b62d4794ba176daef5be"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.2+0/libsharp2.v1.0.2.x86_64-apple-darwin.tar.gz"
[[libsharp2]]
arch = "x86_64"
git-tree-sha1 = "de10ea5f8c45dbda3fa4a81aa71e9e32d49ae341"
libc = "glibc"
os = "linux"

    [[libsharp2.download]]
    sha256 = "de8eea810c34b9cefd9c60ca4a9a269053725e79a155d6f3600767f6de2740cc"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.2+0/libsharp2.v1.0.2.x86_64-linux-gnu.tar.gz"
[[libsharp2]]
arch = "x86_64"
git-tree-sha1 = "1136112100f1295d4d8ef47d2ce0f2bb40a0ee71"
libc = "musl"
os = "linux"

    [[libsharp2.download]]
    sha256 = "2911f9ebdb5b094c03cda1085b212fb2546998b44a1bb3b887101e91b3624e97"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.2+0/libsharp2.v1.0.2.x86_64-linux-musl.tar.gz"
[[libsharp2]]
arch = "x86_64"
git-tree-sha1 = "002562ff0d630810139c19e56e074aebe2671ec2"
os = "freebsd"

    [[libsharp2.download]]
    sha256 = "0cb96b479fbc77d3529f8c5f6ec00ba4b1b156c0f22d3a94ac7c1cdf36d2cbb5"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.2+0/libsharp2.v1.0.2.x86_64-unknown-freebsd.tar.gz"
[[libsharp2]]
arch = "x86_64"
git-tree-sha1 = "030cdba6da5fdbbbc29f5122a7b6115f31428424"
os = "windows"

    [[libsharp2.download]]
    sha256 = "fb7345a59dc7f2e4d9b0afe072ddad389659e8c945a784458c4b8fa6b82d6859"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.2+0/libsharp2.v1.0.2.x86_64-w64-mingw32.tar.gz"
