[[libsharp2]]
arch = "aarch64"
git-tree-sha1 = "cac23c3559bdcf557c2d8546bc0bb98f2b76c960"
os = "macos"

    [[libsharp2.download]]
    sha256 = "015001ec0f773322c4834bd5870e7810b16e3b21b6941629fe64986f49e3fd0c"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.1+0/libsharp2.v1.0.1.aarch64-apple-darwin.tar.gz"
[[libsharp2]]
arch = "aarch64"
git-tree-sha1 = "eec5f91ecb603ba0d3294455313d83737ed0fcee"
libc = "glibc"
os = "linux"

    [[libsharp2.download]]
    sha256 = "15f2148724d103e0efa2c0b75d0469fd220ff7a0d0aa76690d504c16990882ab"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.1+0/libsharp2.v1.0.1.aarch64-linux-gnu.tar.gz"
[[libsharp2]]
arch = "aarch64"
git-tree-sha1 = "6b25606611932ed2f4b8a4551f723eac5a6f4e22"
libc = "musl"
os = "linux"

    [[libsharp2.download]]
    sha256 = "97b919ec9ba4c6cd068ecea87cc943879f87f49e9bac1b739ace4d9997a418df"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.1+0/libsharp2.v1.0.1.aarch64-linux-musl.tar.gz"
[[libsharp2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "912906e52e1d2437065ec547650f16c00e840aa0"
libc = "glibc"
os = "linux"

    [[libsharp2.download]]
    sha256 = "48bb61d429071c743650bf18669ea1ac4bcc3422bf504a14f0c7ca66ecae7031"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.1+0/libsharp2.v1.0.1.armv6l-linux-gnueabihf.tar.gz"
[[libsharp2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "045ce369f4aec1b334d9aa135022c4256db0b791"
libc = "musl"
os = "linux"

    [[libsharp2.download]]
    sha256 = "0969fbd5fe630a1f38aab0265433f38a41676ffcbdfd51df004a2e8ae17d033c"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.1+0/libsharp2.v1.0.1.armv6l-linux-musleabihf.tar.gz"
[[libsharp2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a28b64b59f41f9ff9cde17905d9421b244fb3284"
libc = "glibc"
os = "linux"

    [[libsharp2.download]]
    sha256 = "7c02c6ea394897479dffb99029cf72a60057f5dbb5b5bc55180e7fee92142c76"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.1+0/libsharp2.v1.0.1.armv7l-linux-gnueabihf.tar.gz"
[[libsharp2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ac4e6daedbe97838ecbff3b46a06d326fe45c884"
libc = "musl"
os = "linux"

    [[libsharp2.download]]
    sha256 = "e94f87b2b7fc3ef4792861d2be0d3a3cde86d04add12dd2f78e45cc926ff2891"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.1+0/libsharp2.v1.0.1.armv7l-linux-musleabihf.tar.gz"
[[libsharp2]]
arch = "i686"
git-tree-sha1 = "14c7f2a1e525443741c98118b48abb27704e96f2"
libc = "glibc"
os = "linux"

    [[libsharp2.download]]
    sha256 = "4dde5cf6fffd8649ef6772f355944b8009ff1749fa119b218318ec5aa1cdb4a1"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.1+0/libsharp2.v1.0.1.i686-linux-gnu.tar.gz"
[[libsharp2]]
arch = "i686"
git-tree-sha1 = "821b16479b88dd55f2885b2772e08e6ec509ffba"
libc = "musl"
os = "linux"

    [[libsharp2.download]]
    sha256 = "8bb4cf2686e03257e8c8d414189d23b05e1394ea5b9a85e9cc34169e9c43453e"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.1+0/libsharp2.v1.0.1.i686-linux-musl.tar.gz"
[[libsharp2]]
arch = "i686"
git-tree-sha1 = "59a84417094ac310b82a0f67c017d2e7e336a764"
os = "windows"

    [[libsharp2.download]]
    sha256 = "80c6748d0d70b136f94d8cc3316f8f08990f804726b314830e50e91033742505"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.1+0/libsharp2.v1.0.1.i686-w64-mingw32.tar.gz"
[[libsharp2]]
arch = "powerpc64le"
git-tree-sha1 = "8c89b5204508dcaedf77ed195131c9cebec30cc5"
libc = "glibc"
os = "linux"

    [[libsharp2.download]]
    sha256 = "5ba5da4e75198ba09472d5025226aef5148d2e541923e744c4b0ebfad750059e"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.1+0/libsharp2.v1.0.1.powerpc64le-linux-gnu.tar.gz"
[[libsharp2]]
arch = "x86_64"
git-tree-sha1 = "a19431aa64dbc0b857cc6291123a9fc85f35f085"
os = "macos"

    [[libsharp2.download]]
    sha256 = "853f4babdad37787bbd5d440f32ab747acd3f339ab47fc25c04b6b1376ae5373"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.1+0/libsharp2.v1.0.1.x86_64-apple-darwin.tar.gz"
[[libsharp2]]
arch = "x86_64"
git-tree-sha1 = "de8af3d402c047b240a3f032119fb68e5cda9080"
libc = "glibc"
os = "linux"

    [[libsharp2.download]]
    sha256 = "dfbaae8bdaf6e9202097b288bc023bc2d1e4d96c3ac6a834d15c7aef35096146"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.1+0/libsharp2.v1.0.1.x86_64-linux-gnu.tar.gz"
[[libsharp2]]
arch = "x86_64"
git-tree-sha1 = "86dce31a5cb1349308d8c1fd8f691006c7f93787"
libc = "musl"
os = "linux"

    [[libsharp2.download]]
    sha256 = "fcc3fca860f790eee34946b9a4572932dac8020ce1ce43f0022a7a743f142d9c"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.1+0/libsharp2.v1.0.1.x86_64-linux-musl.tar.gz"
[[libsharp2]]
arch = "x86_64"
git-tree-sha1 = "2a26308c31f4d63dba1cb27bcfeff7cc1bb248cc"
os = "freebsd"

    [[libsharp2.download]]
    sha256 = "9581ef73b28bc765f945e0107c23befb68761e5ce630830cc19c50ad0d7848f4"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.1+0/libsharp2.v1.0.1.x86_64-unknown-freebsd.tar.gz"
[[libsharp2]]
arch = "x86_64"
git-tree-sha1 = "77e2bedf7d1a0f2dbfc400063c490af5406e482c"
os = "windows"

    [[libsharp2.download]]
    sha256 = "3da9df602b0c5e73f58b175fff368fe32351c98652528906e82b72787fec59ac"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.1+0/libsharp2.v1.0.1.x86_64-w64-mingw32.tar.gz"
