[[libsharp2]]
arch = "i686"
git-tree-sha1 = "633149f11a55621c51eb4bbbe76c8517a18af1ec"
libc = "musl"
os = "linux"

    [[libsharp2.download]]
    sha256 = "4f91aca7f4f06067fd467170462f9a66a1dd3d25e10bd9175fdddf007343647f"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.0+1/libsharp2.v1.0.0.i686-linux-musl.tar.gz"
[[libsharp2]]
arch = "aarch64"
git-tree-sha1 = "2c4dd90094676fe42e59f9d1c0fbacffccbc9c4c"
libc = "musl"
os = "linux"

    [[libsharp2.download]]
    sha256 = "c54e6c28aaa10d69363719b74ce8b8ba2275a58d5a53a6eb65c87a7eb1f3074c"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.0+1/libsharp2.v1.0.0.aarch64-linux-musl.tar.gz"
[[libsharp2]]
arch = "i686"
git-tree-sha1 = "8d221ab407d5821aac04e6198fa3adc778515d4a"
os = "windows"

    [[libsharp2.download]]
    sha256 = "233a291077f71d58c016c459a5e5982eaa4d11da7ce980f223fe8749d5ce8db3"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.0+1/libsharp2.v1.0.0.i686-w64-mingw32.tar.gz"
[[libsharp2]]
arch = "x86_64"
git-tree-sha1 = "25343ed5fe7165c5cdc618a97a42c76eeea720e4"
os = "windows"

    [[libsharp2.download]]
    sha256 = "21922eddfc025db7405879422bfb6e888071d5b423d6e5f2fa9f9595baf1c0ad"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.0+1/libsharp2.v1.0.0.x86_64-w64-mingw32.tar.gz"
[[libsharp2]]
arch = "armv7l"
git-tree-sha1 = "94ed1866b1e6ea2d00b18c1b4a7f45d3251f547c"
libc = "glibc"
os = "linux"

    [[libsharp2.download]]
    sha256 = "e6bea15f7585a66785c3eb8b8899c438e887d4d89c264b59ded7acd0c2f72fc5"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.0+1/libsharp2.v1.0.0.armv7l-linux-gnueabihf.tar.gz"
[[libsharp2]]
arch = "armv7l"
git-tree-sha1 = "ee7de3c6678081aa6cac09627d4d944050fea6f8"
libc = "musl"
os = "linux"

    [[libsharp2.download]]
    sha256 = "cc33d4892d9499b2356bb0d99757ad9cc01e6a4c4c6e852ac2faed8e346c27ff"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.0+1/libsharp2.v1.0.0.armv7l-linux-musleabihf.tar.gz"
[[libsharp2]]
arch = "i686"
git-tree-sha1 = "c61b4ed93207f837b5830ed7bbbdad66542f5b41"
libc = "glibc"
os = "linux"

    [[libsharp2.download]]
    sha256 = "808adc481a4fb1cd0120b7bf9157d9c4bfae6301f5f8a7c243f446b115ecae69"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.0+1/libsharp2.v1.0.0.i686-linux-gnu.tar.gz"
[[libsharp2]]
arch = "x86_64"
git-tree-sha1 = "87b399d9cf0efbe37c0a1c4852b4aadf308ba103"
libc = "glibc"
os = "linux"

    [[libsharp2.download]]
    sha256 = "23c9914e33903ebf372ebce45d4bbacca2891e826ad5b68b9efae538274920ce"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.0+1/libsharp2.v1.0.0.x86_64-linux-gnu.tar.gz"
[[libsharp2]]
arch = "powerpc64le"
git-tree-sha1 = "30d4f0e9a6fb1d47a6fbea19146f63d3c4745f66"
libc = "glibc"
os = "linux"

    [[libsharp2.download]]
    sha256 = "1bb989266915b6c5ec828b5ba7f91c259a6803a67860da01ee7ace036acc946b"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.0+1/libsharp2.v1.0.0.powerpc64le-linux-gnu.tar.gz"
[[libsharp2]]
arch = "x86_64"
git-tree-sha1 = "e601815278f7bbd8c4290c0d8dd26c3e53c7aa2c"
os = "macos"

    [[libsharp2.download]]
    sha256 = "db21a3a5cbadd0ca3fa80608a9014d06ab16258f58b34692c76794dc47ec02c8"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.0+1/libsharp2.v1.0.0.x86_64-apple-darwin14.tar.gz"
[[libsharp2]]
arch = "aarch64"
git-tree-sha1 = "a78182a11c2997c8f454b95aa584776f4cab915f"
libc = "glibc"
os = "linux"

    [[libsharp2.download]]
    sha256 = "f997590803c2f75170386c07951224b4912edf7a195d734696108adb33c3e696"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.0+1/libsharp2.v1.0.0.aarch64-linux-gnu.tar.gz"
[[libsharp2]]
arch = "x86_64"
git-tree-sha1 = "a8e71706ff2a0a8337ca81f4032dc16bf4f7ea66"
os = "freebsd"

    [[libsharp2.download]]
    sha256 = "721b085acb78d3dff803c0538bda6cabb5484635152dae47be3c9ba2e5dcade8"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.0+1/libsharp2.v1.0.0.x86_64-unknown-freebsd11.1.tar.gz"
[[libsharp2]]
arch = "x86_64"
git-tree-sha1 = "026346699cc7908c24823d3686709d49f97882cf"
libc = "musl"
os = "linux"

    [[libsharp2.download]]
    sha256 = "43f65348ce32c715fef7806627c185d2690ad51b794dec3dbcaa08096f448312"
    url = "https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases/download/libsharp2-v1.0.0+1/libsharp2.v1.0.0.x86_64-linux-musl.tar.gz"
