# Autogenerated wrapper script for libsharp2_jll for aarch64-apple-darwin
export libsharp2

using LLVMOpenMP_jll
JLLWrappers.@generate_wrapper_header("libsharp2")
JLLWrappers.@declare_library_product(libsharp2, "@rpath/libsharp2.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header(LLVMOpenMP_jll)
    JLLWrappers.@init_library_product(
        libsharp2,
        "lib/libsharp2.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
