# Autogenerated wrapper script for libsharp2_jll for i686-w64-mingw32
export libsharp2

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("libsharp2")
JLLWrappers.@declare_library_product(libsharp2, "libsharp2-0.dll")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libsharp2,
        "bin\\libsharp2-0.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
